module.exports = [
  { data: 'Go grab a glass of water.', enabled: true },
  { data: 'Slowly look all the way left, then right.', enabled: true },
  { data: 'Slowly look all the way up, then down.', enabled: true },
  { data: 'Close your eyes and take few deep breaths.', enabled: true },
  { data: 'Close your eyes and relax.', enabled: true },
  { data: 'Stretch your legs.', enabled: true },
  { data: 'Stretch your arms.', enabled: true },
  { data: 'Is your sitting posture correct?', enabled: true },
  { data: 'Slowly turn head to side and hold for 10 seconds.', enabled: true },
  { data: 'Slowly tilt head to side and hold for 5-10 seconds.', enabled: true },
  { data: 'Stand from chair and stretch.', enabled: true },
  { data: 'Refocus eyes on an object at least 20 meters away.', enabled: true },
  { data: 'Take a moment to think about something you appreciate.', enabled: true },
  { data: 'Take a moment to smile at being alive.', enabled: true },
  { data: 'Truly ergonomic workstation is one that you regularly push away from.', enabled: true },
  { data: 'Close your eyes and count your breaths.', enabled: true },
  { data: 'Close your eyes and name the things you hear.', enabled: true },
  { data: 'Place fingertips on shoulders. Roll shoulders forward for 10 seconds, then backward.', enabled: true },
  { data: 'Raise right arm, stretch it over your head to the left, and hold for 10 seconds. Repeat on other side.', enabled: true },
  { data: 'With right hand, grab each finger of left hand in turn and squeeze. Repeat on other side.', enabled: true },
  { data: 'Stand up and do lunge. Hold for 10 seconds, then do other leg.', enabled: true }
]
