name: Arm Packages build

on:
  push:
    branches:
      - release

env:
  USE_SYSTEM_FPM: true

permissions:
  contents: write

jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update && sudo apt-get install --no-install-recommends -y ruby-full libarchive-tools libinput-dev libudev-dev
    - run: sudo gem install fpm -v 1.15
    - uses: ./.github/actions/setup-build
    - run: node_modules/.bin/electron-builder build
      env:
        GH_TOKEN: ${{ secrets.github_token }}
